# Generated by Django 2.2.1 on 2019-09-07 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cooperatives', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowReservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_reservation', models.BooleanField(default=True)),
                ('cooperative', models.ForeignKey(blank=True, limit_choices_to={'category': 9}, on_delete=django.db.models.deletion.DO_NOTHING, to='cooperatives.Cooperative')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(null=True)),
                ('diners', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('REQUESTED', 'REQUESTED'), ('REPROGRAMED', 'REPROGRAMED'), ('COMPLETED', 'COMPLETED'), ('CANCELED', 'CANCELED')], default='REQUESTED', max_length=20)),
                ('cooperative', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='reservations.AllowReservation')),
            ],
        ),
    ]
